# Generated by Django 2.1.4 on 2018-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('games_count', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('average_game_score', models.FloatField()),
                ('average_user_score', models.FloatField()),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
