# Generated by Django 2.1.4 on 2018-12-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindb',
            name='average_game_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='logindb',
            name='average_user_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='logindb',
            name='games_count',
            field=models.IntegerField(null=True),
        ),
    ]
